language: generic
sudo: required

services: 
  - docker

before_install:
  - docker build -t albertojnk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true albertojnk/react-test npm test

after_success:
  - docker build -t albertojnk/multi-client -f ./client
  - docker build -t albertojnk/multi-nginx -f ./nginx
  - docker build -t albertojnk/multi-server -f ./server
  - docker build -t albertojnk/multi-worker -f ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push albertojnk/multi-client
  - docker push albertojnk/multi-nginx
  - docker push albertojnk/multi-server
  - docker push albertojnk/multi-worker